apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: <crd_name>                        # <plural>.<group>
spec:
  scope: Namespaced                       # Namespaced or Cluster
  group: <api_group>                      # group name to use for REST API: /apis/<group>/<version>
  names:
    plural: <plural_name>
    singular: <singular_name>
    kind: <Kind>
    shortNames:
      - <short_name>
  versions:
    name: v1
    server: true                          # Each version can be enabled/disabled by Served flag
    storage: true
    schema:
      openAPIV3Schema:
        type: Object
        properties:
          image:
            type: string
          replicas:
            type: integer
