apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv_name
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle | Retain | Delete
  awsElasticBlockStore:
    volumeID: volume_id
    fsType: ext4
  hostPath:
    path: "/mnt/data"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc_name
spec:
  storageClassName: manual | normal
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

